# Generated by Django 4.0.2 on 2022-03-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_remove_post_thumbnail_post_cdn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
