# Generated by Django 4.0.2 on 2022-03-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
