# Generated by Django 4.0.2 on 2022-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_pp_cdn_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pp_cdn_url',
            field=models.CharField(max_length=350),
        ),
    ]
